---
- name: "Enable repository sets"
  katello_repository_set:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    organization: "{{ item.0.name }}"
    label: "{{ item.1.label }}"
    repositories: "{{ item.1.repositories }}"
    state: "{{ item.1.state }}"
  with_subelements:
    - "{{ satellite_orgs }}"
    - products
  loop_control:
    label: "{{ item.1.name }}"
  when:
    - item.0.state == "present"
  register: enable_repo_results
  tags: [products]

#- name: Sync Repositories
#  meta: flush_handlers

- name: Create Sync Plans
  katello_sync_plan:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    verify_ssl: "{{ satellite_verify_ssl }}"
    name: "{{ item.1.name }}"
    organization: "{{ item.0.name }}"
    interval: "{{ item.1.interval }}"
    enabled: "{{ item.1.enabled }}"
    sync_date: "{{ item.1.date }}"
    products: "{{ item.1.products }}"
  with_subelements:
    - "{{ satellite_orgs }}"
    - sync_plans
  loop_control:
    label: "{{ item.1.products }}"
  when: configure_katello_sync_plans
  tags: [sync_plans]
  ignore_errors: yes

- debug:
    msg: | 
      Currently the sync plan is created but it does not add products 
      to the sync plan it creates. This why we are ingore_errors for katello_sync_plan.
      Issue #273 as been raised with foreman-ansible-modules.
