---
- name: Create Sync Plans
  katello_sync_plan:
    username: "{{ configure_katello_username }}"
    password: "{{ configure_katello_password }}"
    server_url: "{{ configure_katello_server_url }}"
    verify_ssl: "{{ configure_katello_verify_ssl }}"
    name: "{{ item.1.name }}"
    organization: "{{ item.0.name }}"
    interval: "{{ item.1.interval }}"
    enabled: "{{ item.1.enabled }}"
    sync_date: "{{ item.1.date }}"
    products: "{{ item.1.products }}"
  with_subelements:
    - "{{ configure_katello_organizations }}"
    - sync_plans
  loop_control:
    label: "{{ item.1.products }}"
  when: configure_katello_sync_plans
  tags: [sync_plans]
  ignore_errors: yes

- debug:
    msg: | 
      Currently the sync plan is created but it does not add products 
      to the sync plan it creates. This why we are ingore_errors for katello_sync_plan.
      Issue #273 as been raised with foreman-ansible-modules.
